---
dockitems_persist:
  - name: Firefox Developer Edition
    path: /Applications/Firefox Developer Edition.app
    pos: 1
  - name: Safari
    path: /Applications/Safari.app
    pos: 2
  - name: iTerm
    path: /Applications/iTerm.app
    pos: 3
  - name: Visual Studio Code
    path: /Applications/Visual Studio Code.app
    pos: 4
  - name: Mail
    path: /System/Applications/Mail.app
    pos: 5
  - name: Calendar
    path: /System/Applications/Calendar.app
    pos: 6
  - name: Messages
    path: /System/Applications/Messages.app
    pos: 7
  - name: Signal
    path: /Applications/Signal.app
    pos: 8
  - name: WhatsApp
    path: /Applications/WhatsApp.app
    pos: 9
  - name: Slack
    path: /Applications/Slack.app
    pos: 10
  - name: Element
    path: /Applications/Element.app
    pos: 11
  - name: FaceTime
    path: /System/Applications/FaceTime.app
    pos: 12
  - name: Music
    path: /System/Applications/Music.app
    pos: 13
  - name: System Preferences
    path: /System/Applications/System Preferences.app
    pos: 14
dockitems_remove:
  - Launchpad
  - Maps
  - Photos
  - Contacts
  - Reminders
  - Notes
  - TV
  - Podcasts
  - News
  - Keynote
  - Numbers
  - Pages
  - App Store
# git_email: user@example.com
# git_name: Example User
homebrew_cask_apps:
  - 1password
  - alfred
  - amethyst
  - bettertouchtool
  - dash
  - docker
  - element
  - figma
  - firefox-developer-edition
  - font-fira-code
  - notion
  - postman
  - signal
  - slack
  - vlc
  - whatsapp
homebrew_installed_packages:
  - ffmpeg
  - youtube-dl
  - hashicorp/tap/terraform
homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/cask-versions
  - hashicorp/tap
macos_defaults:
  - domain: NSGlobalDomain
    key: NSDocumentSaveNewDocumentsToCloud
    value: false
    type: bool
  - domain: com.apple.finder
    key: NewWindowTarget
    value: PfHm
    type: string
  - domain: NSGlobalDomain
    key: AppleShowAllExtensions
    value: true
    type: bool
  - domain: com.apple.dock
    key: tilesize
    value: 48
    type: float
  - domain: com.apple.dock
    key: autohide
    value: true
    type: bool
  - domain: com.apple.dock
    key: show-recents
    value: false
    type: bool
  - domain: com.apple.dock
    key: mru-spaces
    value: false
    type: bool
  - domain: NSGlobalDomain
    key: InitialKeyRepeat
    value: 20
    type: int
  - domain: NSGlobalDomain
    key: KeyRepeat
    value: 2
    type: int
  - domain: com.apple.TextEdit
    key: RichText
    value: false
    type: bool
  - domain: com.microsoft.VSCode
    key: ApplePressAndHoldEnabled
    value: false
    type: bool
mas_installed_apps:
  - id: 937984704
    name: Amphetamine
visual_studio_code_extensions:
  - eamodio.gitlens
  - golang.go
  - johnpapa.winteriscoming
  - ms-azuretools.vscode-docker
  - ms-python.python
  - pkief.material-icon-theme
  - vscodevim.vim
  - redhat.ansible
  - rust-lang.rust-analyzer
  - stkb.rewrap
  - streetsidesoftware.code-spell-checker
