---
- name: Install Visual Studio Code
  community.general.homebrew_cask:
    name: visual-studio-code
    state: present
- name: Create code symlink
  ansible.builtin.file:
    src: /Applications/Visual Studio Code.app/Contents/Resources/app/bin/code
    dest: /usr/local/bin/code
    state: link
- name: Install requirements for Ansible extension
  ansible.builtin.pip:
    name: ansible-lint[yamllint]
    executable: pip3
    state: present
- name: Install Visual Studio Code extensions
  import_role:
    name: gantsign.visual-studio-code-extensions
  vars:
    users:
      - username: "{{ ansible_user_id }}"
        visual_studio_code_extensions: "{{ visual_studio_code_extensions }}"
- name: Configure Visual Studio Code
  ansible.builtin.copy:
    src: vscode.json
    dest: "{{ ansible_user_dir }}/Library/Application Support/Code/User/settings.json"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: 0644
- name: Configure Visual Studio Code keybindings
  ansible.builtin.copy:
    src: vscode_keybindings.json
    dest: "{{ ansible_user_dir }}/Library/Application Support/Code/User/keybindings.json"
    owner: "{{ ansible_user_uid }}"
    group: "{{ ansible_user_gid }}"
    mode: 0644
